#eureka:
#  instance:
#    hostname: user-server
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery-server-1:8761/eureka/,http://discovery-server-2:8762/eureka/

spring:
    datasource:
      url: jdbc:mysql://192.168.1.10:3306/solution-server?characterEncoding=utf8&useSSL=true
      username: root
      password: mytest
      driver-class-name: com.mysql.jdbc.Driver

    redis:
      host: 192.168.1.10
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0 
    output:
      ansi:
        enabled: DETECT
        