spring:
  profiles:
    active: dev
logging:
  file: my.log
  
debug: true

#---
# mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=primary"
#spring:
#  profiles: primary
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: designer-service-1
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server-2:8762/eureka/
#
#---
## mvn spring-boot:run -Drun.jvmArguments="-Dspring.profiles.active=secondary"
#spring:
#  profiles: secondary
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: designer-service-2
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server-1:8761/eureka/

